"""
Django settings for cebufitnesshubproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-insecure-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost',
        'http://localhost:8000',
        'http://127.0.0.1',
        'http://127.0.0.1:8000',
    ]
else:
    ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]
    # Required for CSRF when deployed on Render
    CSRF_TRUSTED_ORIGINS = [
        *(o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o),
        'https://*.onrender.com',
    ]

# Honor X-Forwarded-Proto for HTTPS behind Render's proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'gymapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cebufitnesshubproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cebufitnesshubproject.wsgi.application'


# Database
# Use Supabase directly (bypass pgBouncer pooler) by rewriting port/path if needed.
db_url = os.getenv('DATABASE_URL')
if db_url:
    if ':6543' in db_url:
        db_url = db_url.replace(':6543', ':5432')
    if '/pooler' in db_url:
        db_url = db_url.replace('/pooler', '')
    # Ensure we use PgBouncer transaction mode (port 6543) to avoid session limits
    if 'pooler.supabase.com' in db_url and ':5432' in db_url:
        db_url = db_url.replace(':5432', ':6543')
    DATABASES = {
        'default': dj_database_url.parse(
            db_url,
            conn_max_age=0,  # avoid long-lived connections
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=0,
            ssl_require=True,
        )
    }

# Add search_path/ssl options when using PostgreSQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'options': '-c search_path=public',
        'sslmode': 'require',
    })
    # Recommended for PgBouncer transaction pooling
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

#DATABASES = {
#    'default': {
        # ----------------------------------------------------
        # This tells Django to use the SQLite backend
#        'ENGINE': 'django.db.backends.sqlite3',
        
        # This sets the database file path to a file named db.sqlite3 
        # inside your project's base directory.
#        'NAME': BASE_DIR / 'db.sqlite3',
        # ----------------------------------------------------
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'cebufitnesshub',
#        'USER': 'postgres',
#        'PASSWORD': 'postgres',
#        'HOST': 'localhost',
#        'PORT': '5432',
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'gymapp.CustomUser'

# Disable admin logging to fix foreign key constraint issues with custom user model
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django.contrib.admin': {
            'handlers': ['null'],
            'level': 'CRITICAL',
        },
    },
} 

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, # Ensure password is at least 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila' #Philippine time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Where collectstatic places files for production serving
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise for efficient static serving in production
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
