# Generated by Django 5.2.7 on 2025-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy_tracker',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupancy_tracker',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='occupancy_tracker',
            name='default_monthly_fee',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='occupancy_tracker',
            name='gym_name',
            field=models.CharField(default='Cebu Fitness Hub', max_length=100),
        ),
        migrations.AddField(
            model_name='occupancy_tracker',
            name='member_id_prefix',
            field=models.CharField(default='CFH', max_length=5),
        ),
        migrations.AlterField(
            model_name='occupancy_tracker',
            name='capacity_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='occupancy_tracker',
            name='peak_hours_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='occupancy_tracker',
            name='peak_hours_start',
            field=models.TimeField(default='08:00'),
        ),
    ]
