# Generated by Django 5.2.7 on 2025-10-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=20, unique=True)),
                ('position', models.CharField(choices=[('trainer', 'Personal Trainer'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('instructor', 'Fitness Instructor'), ('maintenance', 'Maintenance Staff'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Staff',
                'verbose_name_plural': 'Gym Staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
