# Generated by Django 5.2.6 on 2025-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='confirm_password',
            field=models.CharField(default='some value', max_length=255),
        ),
    ]
