# Generated by Django 5.2.6 on 2025-10-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_gymstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymstaff',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='status',
        ),
        migrations.AddField(
            model_name='gymstaff',
            name='password',
            field=models.CharField(default='pass1234', help_text='Hashed password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymstaff',
            name='staff_id',
            field=models.AutoField(help_text='Unique staff ID', primary_key=True, serialize=False),
        ),
    ]
