# Generated by Django 5.2.6 on 2025-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_memberregistration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='confirm_password',
            field=models.CharField(max_length=255),
        ),
    ]
