# Generated by Django 5.2.7 on 2025-11-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_occupancy_tracker_contact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_record',
            name='new_balance',
        ),
        migrations.RemoveField(
            model_name='gym_member',
            name='monthly_fee',
        ),
    ]
