# Generated by Django 5.2.7 on 2025-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_remove_billing_record_new_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_member',
            name='days_remaining_on_freeze',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
