# Generated by Django 5.2.6 on 2025-10-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_alter_memberregistration_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='memberregistration',
            name='memberID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
