# Generated by Django 5.2.6 on 2025-10-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_rename_contact_number_gymstaff_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gymstaff',
            name='updated_at',
        ),
    ]
