# Generated by Django 5.2.7 on 2025-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_gym_member_days_remaining_on_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='URL to redirect to on click', max_length=255, null=True),
        ),
    ]
