# Generated by Django 5.2.6 on 2025-10-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_remove_gymstaff_created_at_remove_gymstaff_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
    ]
