# Generated by Django 5.2.6 on 2025-10-20 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymstaff',
            name='custom_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
