# Generated by Django 5.2.7 on 2025-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_notification_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_member',
            name='membership_id',
            field=models.CharField(blank=True, help_text='e.g., CFH-2025-0001', max_length=20, null=True, unique=True),
        ),
    ]
