# Generated by Django 5.2.8 on 2025-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_gym_member_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_member',
            name='activation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
