# Generated by Django 5.2.7 on 2025-11-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_gymstaff_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unfreeze_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unfreeze_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
