# Generated by Django 5.2.7 on 2025-11-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_customuser_is_frozen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='freeze_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='freeze_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
