# Generated by Django 5.2.8 on 2025-11-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_gym_member_activation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.gym_member'),
        ),
    ]
