# Generated by Django 5.2.8 on 2025-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_notification_related_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_request',
            name='days_requested',
            field=models.IntegerField(blank=True, help_text='Requested freeze duration in days (1-5)', null=True),
        ),
    ]
